// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMxjvHak2RCMmSGGFCANVGIO2k5tA5uaE',
    appId: '1:268921098409:web:e42f56e4a9604b780c19b8',
    messagingSenderId: '268921098409',
    projectId: 'example-a812c',
    authDomain: 'example-a812c.firebaseapp.com',
    storageBucket: 'example-a812c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBObz8qvP3EL6-QOzL8V94-iGmnT34Cp4c',
    appId: '1:268921098409:android:89cf6190a916dff50c19b8',
    messagingSenderId: '268921098409',
    projectId: 'example-a812c',
    storageBucket: 'example-a812c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIw7tIroLSZQqaAX4sRVzKFU_qcZrdENw',
    appId: '1:268921098409:ios:ff0a98d99d0018e80c19b8',
    messagingSenderId: '268921098409',
    projectId: 'example-a812c',
    storageBucket: 'example-a812c.appspot.com',
    iosClientId: '268921098409-uc1m9rr9mnhsftfv3mg27tl4h4httc59.apps.googleusercontent.com',
    iosBundleId: 'com.example.instantGram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIw7tIroLSZQqaAX4sRVzKFU_qcZrdENw',
    appId: '1:268921098409:ios:ff0a98d99d0018e80c19b8',
    messagingSenderId: '268921098409',
    projectId: 'example-a812c',
    storageBucket: 'example-a812c.appspot.com',
    iosClientId: '268921098409-uc1m9rr9mnhsftfv3mg27tl4h4httc59.apps.googleusercontent.com',
    iosBundleId: 'com.example.instantGram',
  );
}
